import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center w-full h-screen">
        <div>
          <h1 className="text-6xl font-bold"><a href="https://dsolutions.mn/" target="_blank" className="text-blue-500 no-underline">Diverse</a> ERC-20 Faucets</h1>
          <p className="mt-5 font-light text-center text-md"> Available Faucet Networks : Polygon Mumbai </p>
        </div>
      </main>

      <footer className="flex justify-center my-5 border-t-2 border-grey-900">
        <div className="pt-5">
          <p> Powered by <a href="https://dsolutions.mn/" target="_blank" className="ml-1 text-blue-500">Diverse Solutions</a> </p>
        </div>
      </footer>
    </div>
  )
}
